### PR TITLE
Rename root() to reroot()

### PR DESCRIPTION
**Pull request by heavywatal**
## Description

This function extends `phytools::reroot()`, NOT `ape::root()`. The original naming was therefore very confusing and caused conflicts with `ape::root()` on some occasions. This PR fixes the misnaming.

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
then it will have name conflict with `phytools::reroot`, as it was defined as a normal but not generic function.

**Comment by heavywatal** [comment]
Partly agree. There seems no problem for this package because `phytools::reroot` is always referred to as `phytools::reroot` or `phytools_reroot`. Out of the package, users can distinguish them with namespace like `phytools::reroot` and `treeio::reroot`. But some users who use both phytools and treeio without knowing namespace may suffer from the conflict.

In the original version, `treeio::root.phylo` could override `ape::root.phylo`, and calling `ape::root` (even with explicit namespace) for phylo object resulted in calling `treeio::root.phylo`. This is what I want to fix in this PR.

So, any name other than `root` is fine with me. `reroot` seemed just reasonable to me, but of course you can name it whatever you think is right.

**Comment by GuangchuangYu** [comment]
would like to ask @brj1 to join the discussion.

**Comment by heavywatal** [comment]
Just rebased it on `master` to follow the recent updates.

**Comment by GuangchuangYu** [comment]
I think I would keep the method name `root`, but change the default behavior to be consistent with `ape::root` in either `phylo` or `treedata`, with additional feature that is able to root on edge.

In future, I may implement my own rooting function instead of calling `phytools::reroot`.

see also the discussion in <https://www.biostars.org/p/332030/>.

**Comment by heavywatal** [comment]
OK, I would be happy with that if it is consistent with `ape::root` although overriding the method for `phylo` still makes me feel a little anxious. Thanks.

**Pull request closed without merging**
